version: 2

sources:
    - name: staging
      database: evident-display-410312
      schema: properties_dataset

      tables:
          - name: raw_london_properties
          - name: london_postcode_lookup
            

models:

  - name: stg_cleaned_london_properties
    description: London property data scraped from the Rightmove website
    columns:
      - name: id
        description: Unique identifier for a property
      - name: Property_Link
        description: A url to the property listing
      - name: Listing_Type
        description: Outlines whether the listing is new ('Added'), or whether the price has been reduced
      - name: Property_type
        description: One of the following - bungalow, detached, flat, park-home, semi-detached, terraced
      - name: Tenure_Type
        description: One of the following - Leasehold, Freehold, Share of Freehold, Commonhold


