name: Test
on:
  workflow_dispatch:
    inputs:
      test:
        description: Run a test flow
        required: true
        default: 'True'
        type: choice
        options: ['True', 'False']

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: print thing
        run: |
          print(${{ github.events.inputs.test }})
